# Generated by Django 3.0.2 on 2020-05-27 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=50, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Depertment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SessionYear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honours_year', models.CharField(max_length=100, null=True)),
                ('honours_grade', models.CharField(max_length=100, null=True)),
                ('masters_year', models.CharField(max_length=100, null=True)),
                ('masters_grade', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('present_address', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('nid', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('dept_head', models.BooleanField(blank=True, default=False)),
                ('joining_date', models.DateField()),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('parents_number', models.CharField(max_length=50, null=True)),
                ('teacher_img', models.ImageField(upload_to='profile/teacher/')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Depertment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstpaper_code', models.CharField(blank=True, max_length=50, null=True)),
                ('secondpaper_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True)),
                ('optional', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_roll', models.CharField(max_length=100, null=True)),
                ('ssc_reg', models.CharField(max_length=100, null=True)),
                ('ssc_year', models.CharField(max_length=100, null=True)),
                ('ssc_grade', models.CharField(max_length=100, null=True)),
                ('ssc_group', models.CharField(max_length=100, null=True)),
                ('ssc_board', models.CharField(max_length=100, null=True)),
                ('hsc_roll', models.CharField(max_length=100, null=True)),
                ('hsc_reg', models.CharField(max_length=100, null=True)),
                ('hsc_year', models.CharField(max_length=100, null=True)),
                ('hsc_grade', models.CharField(max_length=100, null=True)),
                ('hsc_group', models.CharField(max_length=100, null=True)),
                ('hsc_board', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=100, null=True)),
                ('mothers_name', models.CharField(max_length=100, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('nid', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('present_address', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('parents_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('joining_date', models.DateField()),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('parents_number', models.CharField(max_length=50, null=True)),
                ('staff_img', models.ImageField(upload_to='profile/staff/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepertmentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Depertment')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
        ),
    ]
