# Generated by Django 3.0.2 on 2020-05-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherwilltake',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacherwilltake',
            name='subject',
            field=models.ManyToManyField(to='accounts.Subject'),
        ),
    ]
