# Generated by Django 3.0.2 on 2020-06-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_totalincome_college_examfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReceipt',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField(default=0)),
                ('year', models.CharField(max_length=100, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('tutionfee', models.FloatField(default=0)),
                ('board_examfee', models.FloatField(default=0)),
                ('college_examfee', models.FloatField(default=0)),
                ('college_devfee', models.FloatField(default=0)),
                ('milad_puja', models.FloatField(default=0)),
                ('library_fee', models.FloatField(default=0)),
                ('college_sports_fee', models.FloatField(default=0)),
                ('board_sports_fee', models.FloatField(default=0)),
                ('poor_fund', models.FloatField(default=0)),
                ('donation', models.FloatField(default=0)),
                ('science_and_tech', models.FloatField(default=0)),
                ('computer_lab_fee', models.FloatField(default=0)),
                ('admission_fee', models.FloatField(default=0)),
                ('reg_fee', models.FloatField(default=0)),
                ('college_rovers', models.FloatField(default=0)),
                ('board_rovers', models.FloatField(default=0)),
                ('college_transfer', models.FloatField(default=0)),
                ('id_fee', models.FloatField(default=0)),
                ('certificate_fee', models.FloatField(default=0)),
                ('retention_fee', models.FloatField(default=0)),
                ('testimonial_fee', models.FloatField(default=0)),
                ('paper_magazine', models.FloatField(default=0)),
                ('preactical_fee', models.FloatField(default=0)),
                ('bill', models.FloatField(default=0)),
                ('management_fee', models.FloatField(default=0)),
                ('fourth_paper', models.FloatField(default=0)),
                ('late_fine', models.FloatField(default=0)),
                ('center', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
