# Generated by Django 3.0.2 on 2020-05-27 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200527_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default=datetime.datetime(2020, 5, 27, 13, 47, 46, 828434, tzinfo=utc), upload_to='profile/student/'),
            preserve_default=False,
        ),
    ]
