# Generated by Django 3.0.2 on 2020-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200503_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
