# Generated by Django 3.0.2 on 2020-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankchargeexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bankchargeexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='boardregexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='boardregexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collegedevexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collegedevexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collegeexamexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collegeexamexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='computerlabexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='computerlabexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='conveyanceexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='conveyanceexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='electricexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='electricexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='entertainmentexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='entertainmentexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='govtsalaryexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='govtsalaryexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='houserentandbonusexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='houserentandbonusexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='libraryexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='libraryexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='managementexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='managementexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='miladpujaexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='miladpujaexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='otherexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='otherexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pardonexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pardonexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='poorfundexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='poorfundexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='printingandstationaryexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='printingandstationaryexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scienceandtechnologyexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scienceandtechnologyexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sportsexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sportsexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='telephonebillexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='telephonebillexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='waterexp',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='waterexp',
            name='vauture',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
