# Generated by Django 3.0.2 on 2020-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabout',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
