# Generated by Django 3.0.2 on 2020-05-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200503_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherwilltake',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacherwilltake',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='TeacherWillTake',
        ),
    ]
