# Generated by Django 3.0.2 on 2020-06-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200628_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='parents_number',
            new_name='phone_number_2',
        ),
        migrations.RenameField(
            model_name='teachereducation',
            old_name='honours_year',
            new_name='honours',
        ),
        migrations.RenameField(
            model_name='teachereducation',
            old_name='masters_year',
            new_name='honours_from',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='hsc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='hsc_grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='masters',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='masters_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='phd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='ssc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='ssc_grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachereducation',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
        ),
        migrations.DeleteModel(
            name='TeacherAbout',
        ),
    ]
