# Generated by Django 3.0.2 on 2020-06-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200630_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dept_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
