# Generated by Django 3.0.2 on 2020-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
