# Generated by Django 3.0.2 on 2020-05-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200505_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='dept',
        ),
    ]
