# Generated by Django 3.0.2 on 2020-06-30 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_teacher_dept_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('joining_date', models.DateField()),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('phone_number_2', models.CharField(max_length=50, null=True)),
                ('teacher_img', models.ImageField(upload_to='profile/principal/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalrEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc', models.CharField(max_length=100, null=True)),
                ('ssc_grade', models.CharField(max_length=100, null=True)),
                ('hsc', models.CharField(max_length=100, null=True)),
                ('hsc_grade', models.CharField(max_length=100, null=True)),
                ('honours', models.CharField(max_length=100, null=True)),
                ('honours_from', models.CharField(max_length=100, null=True)),
                ('honours_grade', models.CharField(max_length=100, null=True)),
                ('masters', models.CharField(max_length=100, null=True)),
                ('masters_from', models.CharField(max_length=100, null=True)),
                ('masters_grade', models.CharField(max_length=100, null=True)),
                ('phd', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Principal')),
            ],
        ),
    ]
