# Generated by Django 3.0.2 on 2020-05-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_subject_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Depertment'),
            preserve_default=False,
        ),
    ]
