# Generated by Django 3.0.2 on 2020-06-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='year',
            name='session',
        ),
    ]
