# Generated by Django 3.0.2 on 2020-05-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subject_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
            preserve_default=False,
        ),
    ]
