# Generated by Django 3.0.2 on 2020-06-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_principal_principalreducation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrincipalrEducation',
            new_name='PrincipalEducation',
        ),
    ]
