# Generated by Django 3.0.2 on 2020-05-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_year_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionyear',
            name='dept',
        ),
    ]
