# Generated by Django 3.0.2 on 2020-05-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_sessionyear_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionyear',
            name='session_end',
        ),
        migrations.RemoveField(
            model_name='sessionyear',
            name='session_start',
        ),
    ]
