# Generated by Django 3.0.2 on 2020-06-30 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200630_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default=datetime.datetime(2020, 6, 30, 9, 28, 3, 199928, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
