# Generated by Django 3.0.2 on 2020-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200607_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='monthly',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
