# Generated by Django 3.0.2 on 2020-06-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200607_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donar_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TutionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fee', models.FloatField(default=0)),
                ('college_exam_fee', models.FloatField(default=0)),
                ('board_exam_fee', models.FloatField(default=0)),
                ('admision_fee', models.FloatField(default=0)),
                ('registration_fee', models.FloatField(default=0)),
                ('college_transfer_fee', models.FloatField(default=0)),
                ('id_fee', models.FloatField(default=0)),
                ('certificate_fee', models.FloatField(default=0)),
                ('retention_fee', models.FloatField(default=0)),
                ('tc_fee', models.FloatField(default=0)),
                ('management_fee', models.FloatField(default=0)),
                ('fourth_paper_fee', models.FloatField(default=0)),
                ('late_fee', models.FloatField(default=0)),
                ('center_fee', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OthersCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_dev_fee', models.FloatField(default=0)),
                ('milad_puja_fee', models.FloatField(default=0)),
                ('library_fee', models.FloatField(default=0)),
                ('college_sports_fee', models.FloatField(default=0)),
                ('board_sports_fee', models.FloatField(default=0)),
                ('poor_fund', models.FloatField(default=0)),
                ('science_tech_fee', models.FloatField(default=0)),
                ('computer_lab_fee', models.FloatField(default=0)),
                ('computer_rovers', models.FloatField(default=0)),
                ('board_rovers', models.FloatField(default=0)),
                ('paper_fee', models.FloatField(default=0)),
                ('practical_fee', models.FloatField(default=0)),
                ('bill', models.FloatField(default=0)),
                ('class_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.TutionFee')),
            ],
        ),
    ]
