# Generated by Django 3.0.2 on 2020-06-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_staff_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('joining_date', models.DateField()),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('phone_number_2', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('post', models.CharField(max_length=50, null=True)),
                ('staff_img', models.ImageField(upload_to='profile/staff/')),
            ],
        ),
    ]
