# Generated by Django 3.0.2 on 2020-06-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_otherscharge_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherscharge',
            old_name='computer_rovers',
            new_name='college_rovers',
        ),
    ]
