# Generated by Django 3.0.2 on 2020-06-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200608_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
