# Generated by Django 3.0.2 on 2020-07-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200704_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormalStaff',
        ),
    ]
