# Generated by Django 3.0.2 on 2020-07-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_normalstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtRemuneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
