# Generated by Django 3.0.2 on 2020-06-12 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_monthlypayment_totalpaidmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 12, 4, 43, 15, 163942, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
