# Generated by Django 3.0.2 on 2020-06-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_admissionfee_bankchargeexp_bankinterestfee_boardexamfee_boardregexp_boardroversfee_boardsportsfee_ce'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('govt_reuneration', models.FloatField(default=0)),
                ('hsc_tutionfee', models.FloatField(default=0)),
                ('honours_tutionfee', models.FloatField(default=0)),
                ('degree_tutionfee', models.FloatField(default=0)),
                ('board_examfee', models.FloatField(default=0)),
                ('college_devfee', models.FloatField(default=0)),
                ('milad_puja', models.FloatField(default=0)),
                ('library_fee', models.FloatField(default=0)),
                ('college_sports_fee', models.FloatField(default=0)),
                ('board_sports_fee', models.FloatField(default=0)),
                ('poor_fund', models.FloatField(default=0)),
                ('donation', models.FloatField(default=0)),
                ('bank_interest', models.FloatField(default=0)),
                ('science_and_tech', models.FloatField(default=0)),
                ('computer_lab_fee', models.FloatField(default=0)),
                ('admission_fee', models.FloatField(default=0)),
                ('reg_fee', models.FloatField(default=0)),
                ('college_rovers', models.FloatField(default=0)),
                ('board_rovers', models.FloatField(default=0)),
                ('college_transfer', models.FloatField(default=0)),
                ('id_fee', models.FloatField(default=0)),
                ('certificate_fee', models.FloatField(default=0)),
                ('retention_fee', models.FloatField(default=0)),
                ('testimonial_fee', models.FloatField(default=0)),
                ('paper_magazine', models.FloatField(default=0)),
                ('preactical_fee', models.FloatField(default=0)),
                ('bill', models.FloatField(default=0)),
                ('management_fee', models.FloatField(default=0)),
                ('fourth_paper', models.FloatField(default=0)),
                ('late_fine', models.FloatField(default=0)),
                ('center', models.FloatField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.SessionYear')),
            ],
        ),
        migrations.CreateModel(
            name='TotalEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.SessionYear')),
            ],
        ),
        migrations.CreateModel(
            name='CenterFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
