# Generated by Django 3.0.2 on 2020-06-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_centerfee_totalearning_totalincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalExpances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('govt_salary', models.FloatField(default=0)),
                ('house_rent', models.FloatField(default=0)),
                ('board_reg', models.FloatField(default=0)),
                ('college_exam', models.FloatField(default=0)),
                ('college_dev', models.FloatField(default=0)),
                ('milad_puja', models.FloatField(default=0)),
                ('library_exp', models.FloatField(default=0)),
                ('sports_exp', models.FloatField(default=0)),
                ('poor_fund_exp', models.FloatField(default=0)),
                ('water_exp', models.FloatField(default=0)),
                ('electric_exp', models.FloatField(default=0)),
                ('telephone_exp', models.FloatField(default=0)),
                ('bank_charges', models.FloatField(default=0)),
                ('scinece_and_tech', models.FloatField(default=0)),
                ('computer_lab_exp', models.FloatField(default=0)),
                ('entertainment_exp', models.FloatField(default=0)),
                ('conveyance', models.FloatField(default=0)),
                ('printing_and_stationary', models.FloatField(default=0)),
                ('management_exp', models.FloatField(default=0)),
                ('pardon', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.SessionYear')),
            ],
        ),
    ]
