# Generated by Django 3.0.2 on 2020-06-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_totalexpances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpaidmonths',
            name='monthly_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.MonthlyPayment'),
        ),
    ]
