# Generated by Django 3.0.2 on 2020-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200622_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpaidmonths',
            name='month',
            field=models.TextField(max_length=55, null=True),
        ),
    ]
