# Generated by Django 3.0.2 on 2020-06-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200622_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpaidmonths',
            name='month',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='YearWiseMonths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_year', models.CharField(max_length=55, null=True)),
                ('month', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
