# Generated by Django 3.0.2 on 2020-06-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200622_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearWiseMonths',
        ),
    ]
