# Generated by Django 3.0.2 on 2020-06-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_delete_yearwisemonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='month',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='TotalPaidMonths',
        ),
    ]
