# Generated by Django 3.0.2 on 2020-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_working_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_document',
            field=models.FileField(blank=True, upload_to='notice/documents/'),
        ),
    ]
