# Generated by Django 3.0.2 on 2020-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_working_files', '0003_auto_20200417_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
