# Generated by Django 3.0.2 on 2020-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_working_files', '0005_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='book_writter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
