# Generated by Django 3.0.2 on 2020-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_working_files', '0006_library_book_writter'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='book_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='book_writter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
