# Generated by Django 3.0.2 on 2020-04-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_working_files', '0008_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='book_img',
            new_name='img',
        ),
    ]
