# Generated by Django 3.0.2 on 2020-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_working_files', '0009_auto_20200418_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
