# Generated by Django 3.0.2 on 2020-05-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_working_files', '0010_auto_20200418_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_document',
            field=models.FileField(blank=True, null=True, upload_to='notice/documents/'),
        ),
    ]
